22.1 platform: Get Idea/Binaries tests running (not pass, though)
work around NPE when there's list of explicitly enabled plugins (just detect all plugins). Revert back once "idea.load.plugins.id" handling is fixed.
NoClassDefFoundError for LZ4Factory when tests start (just added missing library)
Deprecated API use in EDTExecutorInternal (gave OOME due to models stuck in the task queue)
MPSHeadlessPlatformStarter - be specific about 'headless', we did a lot of work to state it's headless already - ApplicationStarter.isHeadless, cmd name ends with 'inspect'. With that, don't rely on some external method to say whether we're headless or not.