NoPendingMigrationsTest: make sure mps-devkit classes are accessible
The test fails for 'mps' project, with NoClassDefFoundError: jetbrains/mps/ide/devkit/components/NodeExplorerComponent
when loading ide.mpsdevkit plugin. Seems that IDEA limits plugins to those available in classpath (hence module dependency in testbench.iml).
Provided it's anyway IDEA that controls plugins, I don't see any value in configuring plugins through EnvConfig.
Use of plugin classloaders seems prefered option to me, I don't quite understand why it was forced otherwise with 1ac44c48 (as usual, there's no explanation). EnvConfig setting seems to be just for legacy reason, not to deal with potential change.
I don't worry about the effect here as NoPendingMigrationTest seems to be the only scenario for BaseProjectsTest.