MPS-34871: move kotlin libs when running from sources to lib/
Fixes "NoClassDefFoundError: ...BinaryVersion", which occurred as kotlinx-metadata located in mps-core libs was not loaded when running a test with a new MPS instance.

- These libraries are already bundled in /lib/ in production, this commit unifies the structure when running from sources (so we do not make patch applicable only for local dev)
- Kotlinx-metadata is needed from mps-persistence, kotlin-compiler-client is needed from make-runtime. Both are needed from the core of mps (in ${mps_home}/lib, be it the root lib folder or the mps plugin lib folder), while the previous location (mps-core) was not convenient to load locally (double classloading, need additional declaration...)