Fixed an exception during parameterized intentions instantiation by adding condition
Exception: `java.lang.NullPointerException: Cannot invoke "String.length()" because the return value of "jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations.getString(org.jetbrains.mps.openapi.model.SNode, org.jetbrains.mps.openapi.language.SProperty)" is null`